"""empty message

Revision ID: b3f0cd3872b8
Revises: 7dcac854445c
Create Date: 2020-12-22 19:13:09.907903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f0cd3872b8'
down_revision = '7dcac854445c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_Show',
    sa.Column('Venue_id', sa.Integer(), nullable=False),
    sa.Column('Show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Show_id'], ['Show.id'], ),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('Venue_id', 'Show_id')
    )
    op.drop_table('venue_artist')
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    op.drop_column('Show', 'artist_name')
    op.drop_column('Show', 'venue_name')
    op.drop_column('Show', 'artist_image_link')
    op.drop_column('Venue', 'past_shows')
    op.drop_column('Venue', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('past_shows', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'artist_id')
    op.create_table('venue_artist',
    sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Artist_id'], ['Artist.id'], name='venue_artist_Artist_id_fkey'),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], name='venue_artist_Venue_id_fkey'),
    sa.PrimaryKeyConstraint('Venue_id', 'Artist_id', name='venue_artist_pkey')
    )
    op.drop_table('venue_Show')
    # ### end Alembic commands ###
