"""empty message

Revision ID: c4bdff4b13a3
Revises: b3f0cd3872b8
Create Date: 2020-12-22 23:14:31.142088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bdff4b13a3'
down_revision = 'b3f0cd3872b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_Show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_Show',
    sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Show_id'], ['Show.id'], name='venue_Show_Show_id_fkey'),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], name='venue_Show_Venue_id_fkey'),
    sa.PrimaryKeyConstraint('Venue_id', 'Show_id', name='venue_Show_pkey')
    )
    # ### end Alembic commands ###
